// Generated by gencpp from file rokubimini_msgs/FirmwareUpdateEthercat.msg
// DO NOT EDIT!


#ifndef ROKUBIMINI_MSGS_MESSAGE_FIRMWAREUPDATEETHERCAT_H
#define ROKUBIMINI_MSGS_MESSAGE_FIRMWAREUPDATEETHERCAT_H

#include <ros/service_traits.h>


#include <rokubimini_msgs/FirmwareUpdateEthercatRequest.h>
#include <rokubimini_msgs/FirmwareUpdateEthercatResponse.h>


namespace rokubimini_msgs
{

struct FirmwareUpdateEthercat
{

typedef FirmwareUpdateEthercatRequest Request;
typedef FirmwareUpdateEthercatResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FirmwareUpdateEthercat
} // namespace rokubimini_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rokubimini_msgs::FirmwareUpdateEthercat > {
  static const char* value()
  {
    return "3e589c8a3c17e65c13355340a4ec94ff";
  }

  static const char* value(const ::rokubimini_msgs::FirmwareUpdateEthercat&) { return value(); }
};

template<>
struct DataType< ::rokubimini_msgs::FirmwareUpdateEthercat > {
  static const char* value()
  {
    return "rokubimini_msgs/FirmwareUpdateEthercat";
  }

  static const char* value(const ::rokubimini_msgs::FirmwareUpdateEthercat&) { return value(); }
};


// service_traits::MD5Sum< ::rokubimini_msgs::FirmwareUpdateEthercatRequest> should match
// service_traits::MD5Sum< ::rokubimini_msgs::FirmwareUpdateEthercat >
template<>
struct MD5Sum< ::rokubimini_msgs::FirmwareUpdateEthercatRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rokubimini_msgs::FirmwareUpdateEthercat >::value();
  }
  static const char* value(const ::rokubimini_msgs::FirmwareUpdateEthercatRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rokubimini_msgs::FirmwareUpdateEthercatRequest> should match
// service_traits::DataType< ::rokubimini_msgs::FirmwareUpdateEthercat >
template<>
struct DataType< ::rokubimini_msgs::FirmwareUpdateEthercatRequest>
{
  static const char* value()
  {
    return DataType< ::rokubimini_msgs::FirmwareUpdateEthercat >::value();
  }
  static const char* value(const ::rokubimini_msgs::FirmwareUpdateEthercatRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rokubimini_msgs::FirmwareUpdateEthercatResponse> should match
// service_traits::MD5Sum< ::rokubimini_msgs::FirmwareUpdateEthercat >
template<>
struct MD5Sum< ::rokubimini_msgs::FirmwareUpdateEthercatResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rokubimini_msgs::FirmwareUpdateEthercat >::value();
  }
  static const char* value(const ::rokubimini_msgs::FirmwareUpdateEthercatResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rokubimini_msgs::FirmwareUpdateEthercatResponse> should match
// service_traits::DataType< ::rokubimini_msgs::FirmwareUpdateEthercat >
template<>
struct DataType< ::rokubimini_msgs::FirmwareUpdateEthercatResponse>
{
  static const char* value()
  {
    return DataType< ::rokubimini_msgs::FirmwareUpdateEthercat >::value();
  }
  static const char* value(const ::rokubimini_msgs::FirmwareUpdateEthercatResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROKUBIMINI_MSGS_MESSAGE_FIRMWAREUPDATEETHERCAT_H
