// Generated by gencpp from file rokubimini_msgs/FirmwareUpdateEthercatResponse.msg
// DO NOT EDIT!


#ifndef ROKUBIMINI_MSGS_MESSAGE_FIRMWAREUPDATEETHERCATRESPONSE_H
#define ROKUBIMINI_MSGS_MESSAGE_FIRMWAREUPDATEETHERCATRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rokubimini_msgs
{
template <class ContainerAllocator>
struct FirmwareUpdateEthercatResponse_
{
  typedef FirmwareUpdateEthercatResponse_<ContainerAllocator> Type;

  FirmwareUpdateEthercatResponse_()
    : result(false)  {
    }
  FirmwareUpdateEthercatResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::rokubimini_msgs::FirmwareUpdateEthercatResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rokubimini_msgs::FirmwareUpdateEthercatResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FirmwareUpdateEthercatResponse_

typedef ::rokubimini_msgs::FirmwareUpdateEthercatResponse_<std::allocator<void> > FirmwareUpdateEthercatResponse;

typedef boost::shared_ptr< ::rokubimini_msgs::FirmwareUpdateEthercatResponse > FirmwareUpdateEthercatResponsePtr;
typedef boost::shared_ptr< ::rokubimini_msgs::FirmwareUpdateEthercatResponse const> FirmwareUpdateEthercatResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rokubimini_msgs::FirmwareUpdateEthercatResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rokubimini_msgs::FirmwareUpdateEthercatResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rokubimini_msgs::FirmwareUpdateEthercatResponse_<ContainerAllocator1> & lhs, const ::rokubimini_msgs::FirmwareUpdateEthercatResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rokubimini_msgs::FirmwareUpdateEthercatResponse_<ContainerAllocator1> & lhs, const ::rokubimini_msgs::FirmwareUpdateEthercatResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rokubimini_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rokubimini_msgs::FirmwareUpdateEthercatResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rokubimini_msgs::FirmwareUpdateEthercatResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rokubimini_msgs::FirmwareUpdateEthercatResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rokubimini_msgs::FirmwareUpdateEthercatResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rokubimini_msgs::FirmwareUpdateEthercatResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rokubimini_msgs::FirmwareUpdateEthercatResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rokubimini_msgs::FirmwareUpdateEthercatResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::rokubimini_msgs::FirmwareUpdateEthercatResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::rokubimini_msgs::FirmwareUpdateEthercatResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rokubimini_msgs/FirmwareUpdateEthercatResponse";
  }

  static const char* value(const ::rokubimini_msgs::FirmwareUpdateEthercatResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rokubimini_msgs::FirmwareUpdateEthercatResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n"
;
  }

  static const char* value(const ::rokubimini_msgs::FirmwareUpdateEthercatResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rokubimini_msgs::FirmwareUpdateEthercatResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FirmwareUpdateEthercatResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rokubimini_msgs::FirmwareUpdateEthercatResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rokubimini_msgs::FirmwareUpdateEthercatResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROKUBIMINI_MSGS_MESSAGE_FIRMWAREUPDATEETHERCATRESPONSE_H
