// Generated by gencpp from file rokubimini_msgs/FirmwareUpdateSerialRequest.msg
// DO NOT EDIT!


#ifndef ROKUBIMINI_MSGS_MESSAGE_FIRMWAREUPDATESERIALREQUEST_H
#define ROKUBIMINI_MSGS_MESSAGE_FIRMWAREUPDATESERIALREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rokubimini_msgs
{
template <class ContainerAllocator>
struct FirmwareUpdateSerialRequest_
{
  typedef FirmwareUpdateSerialRequest_<ContainerAllocator> Type;

  FirmwareUpdateSerialRequest_()
    : file_path()  {
    }
  FirmwareUpdateSerialRequest_(const ContainerAllocator& _alloc)
    : file_path(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _file_path_type;
  _file_path_type file_path;





  typedef boost::shared_ptr< ::rokubimini_msgs::FirmwareUpdateSerialRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rokubimini_msgs::FirmwareUpdateSerialRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FirmwareUpdateSerialRequest_

typedef ::rokubimini_msgs::FirmwareUpdateSerialRequest_<std::allocator<void> > FirmwareUpdateSerialRequest;

typedef boost::shared_ptr< ::rokubimini_msgs::FirmwareUpdateSerialRequest > FirmwareUpdateSerialRequestPtr;
typedef boost::shared_ptr< ::rokubimini_msgs::FirmwareUpdateSerialRequest const> FirmwareUpdateSerialRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rokubimini_msgs::FirmwareUpdateSerialRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rokubimini_msgs::FirmwareUpdateSerialRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rokubimini_msgs::FirmwareUpdateSerialRequest_<ContainerAllocator1> & lhs, const ::rokubimini_msgs::FirmwareUpdateSerialRequest_<ContainerAllocator2> & rhs)
{
  return lhs.file_path == rhs.file_path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rokubimini_msgs::FirmwareUpdateSerialRequest_<ContainerAllocator1> & lhs, const ::rokubimini_msgs::FirmwareUpdateSerialRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rokubimini_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rokubimini_msgs::FirmwareUpdateSerialRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rokubimini_msgs::FirmwareUpdateSerialRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rokubimini_msgs::FirmwareUpdateSerialRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rokubimini_msgs::FirmwareUpdateSerialRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rokubimini_msgs::FirmwareUpdateSerialRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rokubimini_msgs::FirmwareUpdateSerialRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rokubimini_msgs::FirmwareUpdateSerialRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a1f82596372c52a517e1fe32d1e998e8";
  }

  static const char* value(const ::rokubimini_msgs::FirmwareUpdateSerialRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa1f82596372c52a5ULL;
  static const uint64_t static_value2 = 0x17e1fe32d1e998e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::rokubimini_msgs::FirmwareUpdateSerialRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rokubimini_msgs/FirmwareUpdateSerialRequest";
  }

  static const char* value(const ::rokubimini_msgs::FirmwareUpdateSerialRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rokubimini_msgs::FirmwareUpdateSerialRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string file_path\n"
;
  }

  static const char* value(const ::rokubimini_msgs::FirmwareUpdateSerialRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rokubimini_msgs::FirmwareUpdateSerialRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.file_path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FirmwareUpdateSerialRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rokubimini_msgs::FirmwareUpdateSerialRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rokubimini_msgs::FirmwareUpdateSerialRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "file_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.file_path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROKUBIMINI_MSGS_MESSAGE_FIRMWAREUPDATESERIALREQUEST_H
