// Generated by gencpp from file rokubimini_msgs/FirmwareUpdateSerial.msg
// DO NOT EDIT!


#ifndef ROKUBIMINI_MSGS_MESSAGE_FIRMWAREUPDATESERIAL_H
#define ROKUBIMINI_MSGS_MESSAGE_FIRMWAREUPDATESERIAL_H

#include <ros/service_traits.h>


#include <rokubimini_msgs/FirmwareUpdateSerialRequest.h>
#include <rokubimini_msgs/FirmwareUpdateSerialResponse.h>


namespace rokubimini_msgs
{

struct FirmwareUpdateSerial
{

typedef FirmwareUpdateSerialRequest Request;
typedef FirmwareUpdateSerialResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FirmwareUpdateSerial
} // namespace rokubimini_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rokubimini_msgs::FirmwareUpdateSerial > {
  static const char* value()
  {
    return "b223f245a1d13c9e179ae29717131752";
  }

  static const char* value(const ::rokubimini_msgs::FirmwareUpdateSerial&) { return value(); }
};

template<>
struct DataType< ::rokubimini_msgs::FirmwareUpdateSerial > {
  static const char* value()
  {
    return "rokubimini_msgs/FirmwareUpdateSerial";
  }

  static const char* value(const ::rokubimini_msgs::FirmwareUpdateSerial&) { return value(); }
};


// service_traits::MD5Sum< ::rokubimini_msgs::FirmwareUpdateSerialRequest> should match
// service_traits::MD5Sum< ::rokubimini_msgs::FirmwareUpdateSerial >
template<>
struct MD5Sum< ::rokubimini_msgs::FirmwareUpdateSerialRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rokubimini_msgs::FirmwareUpdateSerial >::value();
  }
  static const char* value(const ::rokubimini_msgs::FirmwareUpdateSerialRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rokubimini_msgs::FirmwareUpdateSerialRequest> should match
// service_traits::DataType< ::rokubimini_msgs::FirmwareUpdateSerial >
template<>
struct DataType< ::rokubimini_msgs::FirmwareUpdateSerialRequest>
{
  static const char* value()
  {
    return DataType< ::rokubimini_msgs::FirmwareUpdateSerial >::value();
  }
  static const char* value(const ::rokubimini_msgs::FirmwareUpdateSerialRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rokubimini_msgs::FirmwareUpdateSerialResponse> should match
// service_traits::MD5Sum< ::rokubimini_msgs::FirmwareUpdateSerial >
template<>
struct MD5Sum< ::rokubimini_msgs::FirmwareUpdateSerialResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rokubimini_msgs::FirmwareUpdateSerial >::value();
  }
  static const char* value(const ::rokubimini_msgs::FirmwareUpdateSerialResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rokubimini_msgs::FirmwareUpdateSerialResponse> should match
// service_traits::DataType< ::rokubimini_msgs::FirmwareUpdateSerial >
template<>
struct DataType< ::rokubimini_msgs::FirmwareUpdateSerialResponse>
{
  static const char* value()
  {
    return DataType< ::rokubimini_msgs::FirmwareUpdateSerial >::value();
  }
  static const char* value(const ::rokubimini_msgs::FirmwareUpdateSerialResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROKUBIMINI_MSGS_MESSAGE_FIRMWAREUPDATESERIAL_H
