// Generated by gencpp from file rokubimini_msgs/GetSensorConfiguration.msg
// DO NOT EDIT!


#ifndef ROKUBIMINI_MSGS_MESSAGE_GETSENSORCONFIGURATION_H
#define ROKUBIMINI_MSGS_MESSAGE_GETSENSORCONFIGURATION_H

#include <ros/service_traits.h>


#include <rokubimini_msgs/GetSensorConfigurationRequest.h>
#include <rokubimini_msgs/GetSensorConfigurationResponse.h>


namespace rokubimini_msgs
{

struct GetSensorConfiguration
{

typedef GetSensorConfigurationRequest Request;
typedef GetSensorConfigurationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetSensorConfiguration
} // namespace rokubimini_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rokubimini_msgs::GetSensorConfiguration > {
  static const char* value()
  {
    return "81f01bfd9a951b1adf9102125874ff5b";
  }

  static const char* value(const ::rokubimini_msgs::GetSensorConfiguration&) { return value(); }
};

template<>
struct DataType< ::rokubimini_msgs::GetSensorConfiguration > {
  static const char* value()
  {
    return "rokubimini_msgs/GetSensorConfiguration";
  }

  static const char* value(const ::rokubimini_msgs::GetSensorConfiguration&) { return value(); }
};


// service_traits::MD5Sum< ::rokubimini_msgs::GetSensorConfigurationRequest> should match
// service_traits::MD5Sum< ::rokubimini_msgs::GetSensorConfiguration >
template<>
struct MD5Sum< ::rokubimini_msgs::GetSensorConfigurationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rokubimini_msgs::GetSensorConfiguration >::value();
  }
  static const char* value(const ::rokubimini_msgs::GetSensorConfigurationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rokubimini_msgs::GetSensorConfigurationRequest> should match
// service_traits::DataType< ::rokubimini_msgs::GetSensorConfiguration >
template<>
struct DataType< ::rokubimini_msgs::GetSensorConfigurationRequest>
{
  static const char* value()
  {
    return DataType< ::rokubimini_msgs::GetSensorConfiguration >::value();
  }
  static const char* value(const ::rokubimini_msgs::GetSensorConfigurationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rokubimini_msgs::GetSensorConfigurationResponse> should match
// service_traits::MD5Sum< ::rokubimini_msgs::GetSensorConfiguration >
template<>
struct MD5Sum< ::rokubimini_msgs::GetSensorConfigurationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rokubimini_msgs::GetSensorConfiguration >::value();
  }
  static const char* value(const ::rokubimini_msgs::GetSensorConfigurationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rokubimini_msgs::GetSensorConfigurationResponse> should match
// service_traits::DataType< ::rokubimini_msgs::GetSensorConfiguration >
template<>
struct DataType< ::rokubimini_msgs::GetSensorConfigurationResponse>
{
  static const char* value()
  {
    return DataType< ::rokubimini_msgs::GetSensorConfiguration >::value();
  }
  static const char* value(const ::rokubimini_msgs::GetSensorConfigurationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROKUBIMINI_MSGS_MESSAGE_GETSENSORCONFIGURATION_H
