// Generated by gencpp from file rokubimini_msgs/ResetWrenchResponse.msg
// DO NOT EDIT!


#ifndef ROKUBIMINI_MSGS_MESSAGE_RESETWRENCHRESPONSE_H
#define ROKUBIMINI_MSGS_MESSAGE_RESETWRENCHRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rokubimini_msgs
{
template <class ContainerAllocator>
struct ResetWrenchResponse_
{
  typedef ResetWrenchResponse_<ContainerAllocator> Type;

  ResetWrenchResponse_()
    : success(false)  {
    }
  ResetWrenchResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::rokubimini_msgs::ResetWrenchResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rokubimini_msgs::ResetWrenchResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ResetWrenchResponse_

typedef ::rokubimini_msgs::ResetWrenchResponse_<std::allocator<void> > ResetWrenchResponse;

typedef boost::shared_ptr< ::rokubimini_msgs::ResetWrenchResponse > ResetWrenchResponsePtr;
typedef boost::shared_ptr< ::rokubimini_msgs::ResetWrenchResponse const> ResetWrenchResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rokubimini_msgs::ResetWrenchResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rokubimini_msgs::ResetWrenchResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rokubimini_msgs::ResetWrenchResponse_<ContainerAllocator1> & lhs, const ::rokubimini_msgs::ResetWrenchResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rokubimini_msgs::ResetWrenchResponse_<ContainerAllocator1> & lhs, const ::rokubimini_msgs::ResetWrenchResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rokubimini_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rokubimini_msgs::ResetWrenchResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rokubimini_msgs::ResetWrenchResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rokubimini_msgs::ResetWrenchResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rokubimini_msgs::ResetWrenchResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rokubimini_msgs::ResetWrenchResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rokubimini_msgs::ResetWrenchResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rokubimini_msgs::ResetWrenchResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::rokubimini_msgs::ResetWrenchResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::rokubimini_msgs::ResetWrenchResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rokubimini_msgs/ResetWrenchResponse";
  }

  static const char* value(const ::rokubimini_msgs::ResetWrenchResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rokubimini_msgs::ResetWrenchResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::rokubimini_msgs::ResetWrenchResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rokubimini_msgs::ResetWrenchResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResetWrenchResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rokubimini_msgs::ResetWrenchResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rokubimini_msgs::ResetWrenchResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROKUBIMINI_MSGS_MESSAGE_RESETWRENCHRESPONSE_H
