// Generated by gencpp from file rokubimini_msgs/ResetWrench.msg
// DO NOT EDIT!


#ifndef ROKUBIMINI_MSGS_MESSAGE_RESETWRENCH_H
#define ROKUBIMINI_MSGS_MESSAGE_RESETWRENCH_H

#include <ros/service_traits.h>


#include <rokubimini_msgs/ResetWrenchRequest.h>
#include <rokubimini_msgs/ResetWrenchResponse.h>


namespace rokubimini_msgs
{

struct ResetWrench
{

typedef ResetWrenchRequest Request;
typedef ResetWrenchResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetWrench
} // namespace rokubimini_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rokubimini_msgs::ResetWrench > {
  static const char* value()
  {
    return "a01e1ece25b40c645838e2e60d7f441c";
  }

  static const char* value(const ::rokubimini_msgs::ResetWrench&) { return value(); }
};

template<>
struct DataType< ::rokubimini_msgs::ResetWrench > {
  static const char* value()
  {
    return "rokubimini_msgs/ResetWrench";
  }

  static const char* value(const ::rokubimini_msgs::ResetWrench&) { return value(); }
};


// service_traits::MD5Sum< ::rokubimini_msgs::ResetWrenchRequest> should match
// service_traits::MD5Sum< ::rokubimini_msgs::ResetWrench >
template<>
struct MD5Sum< ::rokubimini_msgs::ResetWrenchRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rokubimini_msgs::ResetWrench >::value();
  }
  static const char* value(const ::rokubimini_msgs::ResetWrenchRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rokubimini_msgs::ResetWrenchRequest> should match
// service_traits::DataType< ::rokubimini_msgs::ResetWrench >
template<>
struct DataType< ::rokubimini_msgs::ResetWrenchRequest>
{
  static const char* value()
  {
    return DataType< ::rokubimini_msgs::ResetWrench >::value();
  }
  static const char* value(const ::rokubimini_msgs::ResetWrenchRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rokubimini_msgs::ResetWrenchResponse> should match
// service_traits::MD5Sum< ::rokubimini_msgs::ResetWrench >
template<>
struct MD5Sum< ::rokubimini_msgs::ResetWrenchResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rokubimini_msgs::ResetWrench >::value();
  }
  static const char* value(const ::rokubimini_msgs::ResetWrenchResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rokubimini_msgs::ResetWrenchResponse> should match
// service_traits::DataType< ::rokubimini_msgs::ResetWrench >
template<>
struct DataType< ::rokubimini_msgs::ResetWrenchResponse>
{
  static const char* value()
  {
    return DataType< ::rokubimini_msgs::ResetWrench >::value();
  }
  static const char* value(const ::rokubimini_msgs::ResetWrenchResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROKUBIMINI_MSGS_MESSAGE_RESETWRENCH_H
