// Generated by gencpp from file rokubimini_msgs/SetSensorConfigurationResponse.msg
// DO NOT EDIT!


#ifndef ROKUBIMINI_MSGS_MESSAGE_SETSENSORCONFIGURATIONRESPONSE_H
#define ROKUBIMINI_MSGS_MESSAGE_SETSENSORCONFIGURATIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rokubimini_msgs
{
template <class ContainerAllocator>
struct SetSensorConfigurationResponse_
{
  typedef SetSensorConfigurationResponse_<ContainerAllocator> Type;

  SetSensorConfigurationResponse_()
    : b(false)  {
    }
  SetSensorConfigurationResponse_(const ContainerAllocator& _alloc)
    : b(false)  {
  (void)_alloc;
    }



   typedef uint8_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::rokubimini_msgs::SetSensorConfigurationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rokubimini_msgs::SetSensorConfigurationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetSensorConfigurationResponse_

typedef ::rokubimini_msgs::SetSensorConfigurationResponse_<std::allocator<void> > SetSensorConfigurationResponse;

typedef boost::shared_ptr< ::rokubimini_msgs::SetSensorConfigurationResponse > SetSensorConfigurationResponsePtr;
typedef boost::shared_ptr< ::rokubimini_msgs::SetSensorConfigurationResponse const> SetSensorConfigurationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rokubimini_msgs::SetSensorConfigurationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rokubimini_msgs::SetSensorConfigurationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rokubimini_msgs::SetSensorConfigurationResponse_<ContainerAllocator1> & lhs, const ::rokubimini_msgs::SetSensorConfigurationResponse_<ContainerAllocator2> & rhs)
{
  return lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rokubimini_msgs::SetSensorConfigurationResponse_<ContainerAllocator1> & lhs, const ::rokubimini_msgs::SetSensorConfigurationResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rokubimini_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rokubimini_msgs::SetSensorConfigurationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rokubimini_msgs::SetSensorConfigurationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rokubimini_msgs::SetSensorConfigurationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rokubimini_msgs::SetSensorConfigurationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rokubimini_msgs::SetSensorConfigurationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rokubimini_msgs::SetSensorConfigurationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rokubimini_msgs::SetSensorConfigurationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88c93a4e354c9b18b18fde29f72f94c2";
  }

  static const char* value(const ::rokubimini_msgs::SetSensorConfigurationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88c93a4e354c9b18ULL;
  static const uint64_t static_value2 = 0xb18fde29f72f94c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::rokubimini_msgs::SetSensorConfigurationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rokubimini_msgs/SetSensorConfigurationResponse";
  }

  static const char* value(const ::rokubimini_msgs::SetSensorConfigurationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rokubimini_msgs::SetSensorConfigurationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"bool b\n"
;
  }

  static const char* value(const ::rokubimini_msgs::SetSensorConfigurationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rokubimini_msgs::SetSensorConfigurationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetSensorConfigurationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rokubimini_msgs::SetSensorConfigurationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rokubimini_msgs::SetSensorConfigurationResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "b: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROKUBIMINI_MSGS_MESSAGE_SETSENSORCONFIGURATIONRESPONSE_H
