// Generated by gencpp from file rokubimini_msgs/SetSensorConfigurationRequest.msg
// DO NOT EDIT!


#ifndef ROKUBIMINI_MSGS_MESSAGE_SETSENSORCONFIGURATIONREQUEST_H
#define ROKUBIMINI_MSGS_MESSAGE_SETSENSORCONFIGURATIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rokubimini_msgs
{
template <class ContainerAllocator>
struct SetSensorConfigurationRequest_
{
  typedef SetSensorConfigurationRequest_<ContainerAllocator> Type;

  SetSensorConfigurationRequest_()
    : a(false)  {
    }
  SetSensorConfigurationRequest_(const ContainerAllocator& _alloc)
    : a(false)  {
  (void)_alloc;
    }



   typedef uint8_t _a_type;
  _a_type a;





  typedef boost::shared_ptr< ::rokubimini_msgs::SetSensorConfigurationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rokubimini_msgs::SetSensorConfigurationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetSensorConfigurationRequest_

typedef ::rokubimini_msgs::SetSensorConfigurationRequest_<std::allocator<void> > SetSensorConfigurationRequest;

typedef boost::shared_ptr< ::rokubimini_msgs::SetSensorConfigurationRequest > SetSensorConfigurationRequestPtr;
typedef boost::shared_ptr< ::rokubimini_msgs::SetSensorConfigurationRequest const> SetSensorConfigurationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rokubimini_msgs::SetSensorConfigurationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rokubimini_msgs::SetSensorConfigurationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rokubimini_msgs::SetSensorConfigurationRequest_<ContainerAllocator1> & lhs, const ::rokubimini_msgs::SetSensorConfigurationRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rokubimini_msgs::SetSensorConfigurationRequest_<ContainerAllocator1> & lhs, const ::rokubimini_msgs::SetSensorConfigurationRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rokubimini_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rokubimini_msgs::SetSensorConfigurationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rokubimini_msgs::SetSensorConfigurationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rokubimini_msgs::SetSensorConfigurationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rokubimini_msgs::SetSensorConfigurationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rokubimini_msgs::SetSensorConfigurationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rokubimini_msgs::SetSensorConfigurationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rokubimini_msgs::SetSensorConfigurationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "685b546c53fb0b7de5dfef48cf30fe1f";
  }

  static const char* value(const ::rokubimini_msgs::SetSensorConfigurationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x685b546c53fb0b7dULL;
  static const uint64_t static_value2 = 0xe5dfef48cf30fe1fULL;
};

template<class ContainerAllocator>
struct DataType< ::rokubimini_msgs::SetSensorConfigurationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rokubimini_msgs/SetSensorConfigurationRequest";
  }

  static const char* value(const ::rokubimini_msgs::SetSensorConfigurationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rokubimini_msgs::SetSensorConfigurationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool a\n"
"\n"
;
  }

  static const char* value(const ::rokubimini_msgs::SetSensorConfigurationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rokubimini_msgs::SetSensorConfigurationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetSensorConfigurationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rokubimini_msgs::SetSensorConfigurationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rokubimini_msgs::SetSensorConfigurationRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "a: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROKUBIMINI_MSGS_MESSAGE_SETSENSORCONFIGURATIONREQUEST_H
