// Generated by gencpp from file rokubimini_msgs/SetSensorConfiguration.msg
// DO NOT EDIT!


#ifndef ROKUBIMINI_MSGS_MESSAGE_SETSENSORCONFIGURATION_H
#define ROKUBIMINI_MSGS_MESSAGE_SETSENSORCONFIGURATION_H

#include <ros/service_traits.h>


#include <rokubimini_msgs/SetSensorConfigurationRequest.h>
#include <rokubimini_msgs/SetSensorConfigurationResponse.h>


namespace rokubimini_msgs
{

struct SetSensorConfiguration
{

typedef SetSensorConfigurationRequest Request;
typedef SetSensorConfigurationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSensorConfiguration
} // namespace rokubimini_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rokubimini_msgs::SetSensorConfiguration > {
  static const char* value()
  {
    return "81f01bfd9a951b1adf9102125874ff5b";
  }

  static const char* value(const ::rokubimini_msgs::SetSensorConfiguration&) { return value(); }
};

template<>
struct DataType< ::rokubimini_msgs::SetSensorConfiguration > {
  static const char* value()
  {
    return "rokubimini_msgs/SetSensorConfiguration";
  }

  static const char* value(const ::rokubimini_msgs::SetSensorConfiguration&) { return value(); }
};


// service_traits::MD5Sum< ::rokubimini_msgs::SetSensorConfigurationRequest> should match
// service_traits::MD5Sum< ::rokubimini_msgs::SetSensorConfiguration >
template<>
struct MD5Sum< ::rokubimini_msgs::SetSensorConfigurationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rokubimini_msgs::SetSensorConfiguration >::value();
  }
  static const char* value(const ::rokubimini_msgs::SetSensorConfigurationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rokubimini_msgs::SetSensorConfigurationRequest> should match
// service_traits::DataType< ::rokubimini_msgs::SetSensorConfiguration >
template<>
struct DataType< ::rokubimini_msgs::SetSensorConfigurationRequest>
{
  static const char* value()
  {
    return DataType< ::rokubimini_msgs::SetSensorConfiguration >::value();
  }
  static const char* value(const ::rokubimini_msgs::SetSensorConfigurationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rokubimini_msgs::SetSensorConfigurationResponse> should match
// service_traits::MD5Sum< ::rokubimini_msgs::SetSensorConfiguration >
template<>
struct MD5Sum< ::rokubimini_msgs::SetSensorConfigurationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rokubimini_msgs::SetSensorConfiguration >::value();
  }
  static const char* value(const ::rokubimini_msgs::SetSensorConfigurationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rokubimini_msgs::SetSensorConfigurationResponse> should match
// service_traits::DataType< ::rokubimini_msgs::SetSensorConfiguration >
template<>
struct DataType< ::rokubimini_msgs::SetSensorConfigurationResponse>
{
  static const char* value()
  {
    return DataType< ::rokubimini_msgs::SetSensorConfiguration >::value();
  }
  static const char* value(const ::rokubimini_msgs::SetSensorConfigurationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROKUBIMINI_MSGS_MESSAGE_SETSENSORCONFIGURATION_H
